### ISSUE TITLE
For what version ? 

### ISSUE THREAD

**Issue by Felix-Jonathan** [cj89898/DeluxeMenus-DeluxeShop#1]
Hello ! 

I just want to know if I did it wrong with my 1.16.5 or it's really for 1.18 ...
Just i want you to know GG for the great job ! I really want to use your plugin :(

![image](https://user-images.githubusercontent.com/115706788/200562660-8f4fd433-369a-477d-8609-19a0f0ed1f28.png)

**Comment by cj89898** [comment]
I think the API just needs to be changed to whatever version you use in the plugin.yml.

You can open the jar with winrar or something to edit this

Edit: Not sure if it will work 100% on 1.16 as it's not tested, but most likely okay.

**Comment by Felix-Jonathan** [comment]
Okey ! It works ! You say the truth ! 

Another problem, I don't have a /shop command

**Comment by cj89898** [comment]
Could you add me on discord? cj89898#7801
